{{- if and .Values.imageCredentials.username .Values.imageCredentials.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cpnConsole.name" . }}-pullsecret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "cpnConsole.imagePullSecret" . }}
{{- end }}
