---
kind: ConfigMap
apiVersion: v1
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    enableUserWorkload: true
    prometheusK8s:
      resources:
      {{- toYaml .Values.prometheus.resources | nindent 8 }}
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: {{ .Values.prometheus.pvc.size }}