apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kibana
  namespace: openshift-logging
spec:
  host: logging.apps.c7.numerique-interieur.com
  to:
      kind: Service
      name: kibana
      weight: 100
