---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
 labels:
   app: {{ include "velero.name" . }}
   prometheus: k8s
   role: alert-rules
 name: {{ include "velero.fullname" . }}-alerts
 namespace: {{ include "velero.namespace" . }}
spec:
 groups:
 - name: {{ include "velero.name" . }}_alerts
   {{- with .Values.prometheusRules.rules }}
   rules:
    {{- toYaml . | nindent 4 }}
   {{- end }}