---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
 labels:
   prometheus: k8s
   role: alert-rules
 name: velero-alerts
 namespace: "{{ .Values.namespace_adp }}"
spec:
 groups:
 - name: velero_alerts
   rules:
   - alert: VeleroBackupFailed
     expr: increase(velero_backup_failure_total[1h]) > 0
     for: 5m
     labels:
       severity: critical
     annotations:
       summary: "Velero backup failure detected"
       description: "The Velero backup has failed. Investigate immediately."
   - alert: VeleroBackupPartialFailed
     expr: increase(velero_backup_partial_failure_total[1h])> 0
     for: 5m
     labels:
       severity: critical
     annotations:
       summary: "Velero backup partial failure detected"
       description: "The Velero backup has some partial backup failure. Take a look"