kind: CronJob
apiVersion: batch/v1
metadata:
  name: velero-backup-job
  namespace: infra-backup-projects
spec:
  schedule: "{{ .Values.schedule_cron }}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    metadata:
      labels:
        app: projects-backup
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: projects-backup
        spec:
          containers:
          - name: backup
            image: registry.redhat.io/openshift4/ose-cli:v4.11
            securityContext:
              privileged: true
            command: ["/bin/sh", "-c"]
            args: ["echo 'ZXhwb3J0IHZlbGVyb05hbWVTcGFjZT1vcGVuc2hpZnQtYWRwCmV4cG9ydCBzdG9yYWdlTG9jYXRpb249dmVsZXJvLTEKCmlmIGt1YmVjdGwgZ2V0IHNjaGVkdWxlIGNsdXN0ZXItcmVzb3VyY2VzIC1uICR7dmVsZXJvTmFtZVNwYWNlfSAmPiAvZGV2L251bGw7IHRoZW4KICBlY2hvICJMZSBzY2hlZHVsZSAnY2x1c3Rlci1yZXNvdXJjZXMnIGV4aXN0ZS4iCmVsc2UKICBjYXQgPDxFT0YgfGt1YmVjdGwgLW4gJHt2ZWxlcm9OYW1lU3BhY2V9IGFwcGx5IC1mIC0KYXBpVmVyc2lvbjogdmVsZXJvLmlvL3YxCmtpbmQ6IFNjaGVkdWxlCm1ldGFkYXRhOgogIG5hbWU6IGNsdXN0ZXItcmVzb3VyY2VzCiAgbmFtZXNwYWNlOiAke3ZlbGVyb05hbWVTcGFjZX0Kc3BlYzoKICBzY2hlZHVsZTogJzAgMCAqICogKiAnCiAgdGVtcGxhdGU6CiAgICBkZWZhdWx0Vm9sdW1lc1RvUmVzdGljOiB0cnVlCiAgICBpbmNsdWRlQ2x1c3RlclJlc291cmNlczogdHJ1ZQogICAgc3RvcmFnZUxvY2F0aW9uOiAke3N0b3JhZ2VMb2NhdGlvbn0KICAgIHR0bDogMjQwaDBtMHMKICAgIGluY2x1ZGVkTmFtZXNwYWNlczoKICAgICAgLSBkZWZhdWx0CkVPRgpmaQoKIyBJbml0aWFsaXNhdGlvbiBkZXMgdmFyaWFibGVzIG1pbnV0ZSBldCBoZXVyZQptaW51dGU9MApoZXVyZT0wCgprdWJlY3RsIGdldCBuYW1lc3BhY2VzIC1vIGN1c3RvbS1jb2x1bW5zPSJOQU1FOi5tZXRhZGF0YS5uYW1lIiB8dGFpbCAtbiArMiB8d2hpbGUgcmVhZCBuYW1lU3BhY2UgO2RvCiAgZXhwb3J0IHNjaGVkdWxlTmFtZT0ke25hbWVTcGFjZX0KICBleHBvcnQgbmFtZVNwYWNlCiAgICAjIEluY3LDqW1lbnRhdGlvbiBkZSBsYSB2YXJpYWJsZSBtaW51dGUKICBtaW51dGU9JCgobWludXRlICsgNSkpCgogICMgSW5jcsOpbWVudGF0aW9uIGRlIGxhIHZhcmlhYmxlIGhldXJlIHNpIG1pbnV0ZSBhdHRlaW50IG91IGTDqXBhc3NlIDYwCiAgaWYgWyAkbWludXRlIC1nZSA2MCBdOyB0aGVuCiAgICBtaW51dGU9MAogICAgaGV1cmU9JCgoaGV1cmUgKyAxKSkKICBmaQoKICAjIFLDqWluaXRpYWxpc2F0aW9uIGRlIGxhIHZhcmlhYmxlIGhldXJlIHNpIGVsbGUgYXR0ZWludCBvdSBkw6lwYXNzZSAyNAogIGlmIFsgJGhldXJlIC1nZSAyNCBdOyB0aGVuCiAgICBoZXVyZT0wCiAgZmkKCiAgY2F0IDw8RU9GIHxrdWJlY3RsIC1uICR7dmVsZXJvTmFtZVNwYWNlfSBhcHBseSAtZiAtCmFwaVZlcnNpb246IHZlbGVyby5pby92MQpraW5kOiBTY2hlZHVsZQptZXRhZGF0YToKICBuYW1lOiAke3NjaGVkdWxlTmFtZX0KICBuYW1lc3BhY2U6ICR7dmVsZXJvTmFtZVNwYWNlfQpzcGVjOgogIHNjaGVkdWxlOiAnJHttaW51dGV9ICR7aGV1cmV9ICogKiAqJwogIHRlbXBsYXRlOgogICAgc3RvcmFnZUxvY2F0aW9uOiAke3N0b3JhZ2VMb2NhdGlvbn0KICAgIHR0bDogMjQwaDBtMHMKICAgIGRlZmF1bHRWb2x1bWVzVG9SZXN0aWM6IHRydWUKICAgIGluY2x1ZGVkTmFtZXNwYWNlczoKICAgICAgLSAke25hbWVTcGFjZX0KRU9GCmRvbmUK' | base64 -d | bash"]
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
          activeDeadlineSeconds: 600
          dnsPolicy: "ClusterFirst"
          serviceAccount: "projects-backup"
          serviceAccountName: projects-backup
