kind: CronJob
apiVersion: batch/v1
metadata:
  name: velero-backup-job
  namespace: "{{ .Values.namespace_adp }}"
spec:
  schedule: "{{ .Values.schedule_cron }}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    metadata:
      labels:
        app: projects-backup
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: projects-backup
        spec:
          containers:
          - name: backup
            image: registry.redhat.io/openshift4/ose-cli:v4.11
            securityContext:
              privileged: true
            command: ["/bin/sh", "-c"]
            args: ["echo 'ZXhwb3J0IHZlbGVyb05hbWVTcGFjZT1vcGVuc2hpZnQtYWRwCmV4cG9ydCBzdG9yYWdlTG9jYXRpb249dmVsZXJvLTEKCmt1YmVjdGwgZ2V0IG5zIC0tc2VsZWN0b3I9c2F2ZS1ieS12ZWxlcm8hPXRydWUgLW8gY3VzdG9tLWNvbHVtbnM9Ik5BTUU6Lm1ldGFkYXRhLm5hbWUifHdoaWxlIHJlYWQgbmFtZVNwYWNlIDtkbwogIGV4cG9ydCBzY2hlZHVsZU5hbWU9JHtuYW1lU3BhY2V9CiAgZXhwb3J0IG5hbWVTcGFjZQogIGt1YmVjdGwgZGVsZXRlIHNjaGVkdWxlICR7c2NoZWR1bGVOYW1lfSAtbiBvcGVuc2hpZnQtYWRwCmRvbmUKCgppZiBrdWJlY3RsIGdldCBzY2hlZHVsZSBjbHVzdGVyLXJlc291cmNlcyAtbiAke3ZlbGVyb05hbWVTcGFjZX0gJj4gL2Rldi9udWxsOyB0aGVuCiAgZWNobyAiTGUgc2NoZWR1bGUgJ2NsdXN0ZXItcmVzb3VyY2VzJyBleGlzdGUuIgplbHNlCiAgY2F0IDw8RU9GIHxrdWJlY3RsIC1uICR7dmVsZXJvTmFtZVNwYWNlfSBhcHBseSAtZiAtCmFwaVZlcnNpb246IHZlbGVyby5pby92MQpraW5kOiBTY2hlZHVsZQptZXRhZGF0YToKICBuYW1lOiBjbHVzdGVyLXJlc291cmNlcwogIG5hbWVzcGFjZTogJHt2ZWxlcm9OYW1lU3BhY2V9CnNwZWM6CiAgc2NoZWR1bGU6ICcwIDAgKiAqICogJwogIHRlbXBsYXRlOgogICAgZGVmYXVsdFZvbHVtZXNUb1Jlc3RpYzogdHJ1ZQogICAgaW5jbHVkZUNsdXN0ZXJSZXNvdXJjZXM6IHRydWUKICAgIHN0b3JhZ2VMb2NhdGlvbjogJHtzdG9yYWdlTG9jYXRpb259CiAgICB0dGw6IDI0MGgwbTBzCkVPRgpmaQoKa3ViZWN0bCBnZXQgbmFtZXNwYWNlcyAtLXNlbGVjdG9yPXNhdmVkLWJ5LXZlbGVybz10cnVlIC1vIGN1c3RvbS1jb2x1bW5zPSJOQU1FOi5tZXRhZGF0YS5uYW1lIiB8dGFpbCAtbiArMiB8d2hpbGUgcmVhZCBuYW1lU3BhY2UgO2RvCiAgZXhwb3J0IHNjaGVkdWxlTmFtZT0ke25hbWVTcGFjZX0KICBleHBvcnQgbmFtZVNwYWNlCiAgICAjIEluY3LDqW1lbnRhdGlvbiBkZSBsYSB2YXJpYWJsZSBtaW51dGUKICBtaW51dGU9JCgobWludXRlICsgNSkpCgogICMgSW5jcsOpbWVudGF0aW9uIGRlIGxhIHZhcmlhYmxlIGhldXJlIHNpIG1pbnV0ZSBhdHRlaW50IG91IGTDqXBhc3NlIDYwCiAgaWYgWyAkbWludXRlIC1nZSA2MCBdOyB0aGVuCiAgICBtaW51dGU9MAogICAgaGV1cmU9JCgoaGV1cmUgKyAxKSkKICBmaQoKICAjIFLDqWluaXRpYWxpc2F0aW9uIGRlIGxhIHZhcmlhYmxlIGhldXJlIHNpIGVsbGUgYXR0ZWludCBvdSBkw6lwYXNzZSAyNAogIGlmIFsgJGhldXJlIC1nZSAyNCBdOyB0aGVuCiAgICBoZXVyZT0wCiAgZmkKCiAgY2F0IDw8RU9GIHxrdWJlY3RsIC1uICR7dmVsZXJvTmFtZVNwYWNlfSBhcHBseSAtZiAtCmFwaVZlcnNpb246IHZlbGVyby5pby92MQpraW5kOiBTY2hlZHVsZQptZXRhZGF0YToKICBuYW1lOiAke3NjaGVkdWxlTmFtZX0KICBuYW1lc3BhY2U6ICR7dmVsZXJvTmFtZVNwYWNlfQpzcGVjOgogIHNjaGVkdWxlOiAnMCAwICogKiAqICcKICB0ZW1wbGF0ZToKICAgIHN0b3JhZ2VMb2NhdGlvbjogJHtzdG9yYWdlTG9jYXRpb259CiAgICB0dGw6IDI0MGgwbTBzCiAgICBkZWZhdWx0Vm9sdW1lc1RvUmVzdGljOiB0cnVlCiAgICBpbmNsdWRlZE5hbWVzcGFjZXM6CiAgICAgIC0gJHtuYW1lU3BhY2V9CkVPRgpkb25lCg==' | base64 -d | bash"]
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
          activeDeadlineSeconds: 600
          dnsPolicy: "ClusterFirst"
          serviceAccount: "projects-backup"
          serviceAccountName: projects-backup