---
kind: CronJob
apiVersion: batch/v1
metadata:
  name: velero-backup-job
  namespace: infra-backup-projects
spec:
  schedule: "{{ .Values.schedule_cron }}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    metadata:
      labels:
        app: projects-backup
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: projects-backup
        spec:
          containers:
          - name: backup
            image: registry.redhat.io/openshift4/ose-cli:v4.11
            securityContext:
              privileged: true
            command: ["/bin/sh", "-c"]
            args: ["echo 'ZXhwb3J0IHZlbGVyb05hbWVTcGFjZT1vcGVuc2hpZnQtYWRwCmV4cG9ydCBzdG9yYWdlTG9jYXRpb249dmVsZXJvLTEKCmlmIGt1YmVjdGwgZ2V0IHNjaGVkdWxlIGNsdXN0ZXItcmVzb3VyY2VzIC1uICR7dmVsZXJvTmFtZVNwYWNlfSAmPiAvZGV2L251bGw7IHRoZW4KICBlY2hvICJMZSBzY2hlZHVsZSAnY2x1c3Rlci1yZXNvdXJjZXMnIGV4aXN0ZS4iCmVsc2UKICBjYXQgPDxFT0YgfGt1YmVjdGwgLW4gJHt2ZWxlcm9OYW1lU3BhY2V9IGFwcGx5IC1mIC0KYXBpVmVyc2lvbjogdmVsZXJvLmlvL3YxCmtpbmQ6IFNjaGVkdWxlCm1ldGFkYXRhOgogIG5hbWU6IGNsdXN0ZXItcmVzb3VyY2VzCiAgbmFtZXNwYWNlOiAke3ZlbGVyb05hbWVTcGFjZX0Kc3BlYzoKICBzY2hlZHVsZTogJzAgMCAqICogKiAnCiAgdGVtcGxhdGU6CiAgICBkZWZhdWx0Vm9sdW1lc1RvUmVzdGljOiB0cnVlCiAgICBpbmNsdWRlQ2x1c3RlclJlc291cmNlczogdHJ1ZQogICAgc3RvcmFnZUxvY2F0aW9uOiAke3N0b3JhZ2VMb2NhdGlvbn0KICAgIHR0bDogMjQwaDBtMHMKICAgIGluY2x1ZGVkTmFtZXNwYWNlczoKICAgICAgLSBkZWZhdWx0CkVPRgpmaQoKa3ViZWN0bCBnZXQgbnMgLS1zZWxlY3Rvcj1zYXZlZC1ieS12ZWxlcm8hPXRydWUgLW8gY3VzdG9tLWNvbHVtbnM9Ik5BTUU6Lm1ldGFkYXRhLm5hbWUifHdoaWxlIHJlYWQgbmFtZVNwYWNlIDtkbwogIGV4cG9ydCBzY2hlZHVsZU5hbWU9JHtuYW1lU3BhY2V9CiAgZXhwb3J0IG5hbWVTcGFjZQogICAgIyBWw6lyaWZpZXIgc2kgbGUgc2NoZWR1bGUgZXhpc3RlIGTDqWrDoAogIGlmIGt1YmVjdGwgZ2V0IHNjaGVkdWxlICR7c2NoZWR1bGVOYW1lfSAtbiBvcGVuc2hpZnQtYWRwICY+L2Rldi9udWxsOyB0aGVuCiAgICBlY2hvICJMZSBzY2hlZHVsZSAke3NjaGVkdWxlTmFtZX0gZXhpc3RlIGTDqWrDoCwgaWwgc2VyYSBzdXBwcmltw6kuIgogICAga3ViZWN0bCBkZWxldGUgc2NoZWR1bGUgJHtzY2hlZHVsZU5hbWV9IC1uIG9wZW5zaGlmdC1hZHAKICBlbHNlCiAgICBlY2hvICJMZSBzY2hlZHVsZSAke3NjaGVkdWxlTmFtZX0gbidleGlzdGUgcGFzIgogIGZpCmRvbmUKCiMgSW5pdGlhbGlzYXRpb24gZGVzIHZhcmlhYmxlcyBtaW51dGUgZXQgaGV1cmUKbWludXRlPTAKaGV1cmU9MAoKa3ViZWN0bCBnZXQgIG5zIC0tc2VsZWN0b3I9c2F2ZWQtYnktdmVsZXJvPXRydWUgLW8gY3VzdG9tLWNvbHVtbnM9Ik5BTUU6Lm1ldGFkYXRhLm5hbWUiIHx0YWlsIC1uICsyIHx3aGlsZSByZWFkIG5hbWVTcGFjZSA7ZG8KICBleHBvcnQgc2NoZWR1bGVOYW1lPSR7bmFtZVNwYWNlfQogIGV4cG9ydCBuYW1lU3BhY2UKCiAgIyBWw6lyaWZpY2F0aW9uIHNpIGxlIHNjaGVkdWxlIGV4aXN0ZSBkw6lqw6AKICBpZiBrdWJlY3RsIGdldCBzY2hlZHVsZSAke3NjaGVkdWxlTmFtZX0gLW4gJHt2ZWxlcm9OYW1lU3BhY2V9ICY+IC9kZXYvbnVsbDsgdGhlbgogICAgZWNobyAiTGUgc2NoZWR1bGUgJHtzY2hlZHVsZU5hbWV9IGV4aXN0ZSBkw6lqw6AuIgogIGVsc2UKCiAgICAjIEluY3LDqW1lbnRhdGlvbiBkZSBsYSB2YXJpYWJsZSBtaW51dGUKICAgIG1pbnV0ZT0kKChtaW51dGUgKyA1KSkKCiAgICAjIEluY3LDqW1lbnRhdGlvbiBkZSBsYSB2YXJpYWJsZSBoZXVyZSBzaSBtaW51dGUgYXR0ZWludCBvdSBkw6lwYXNzZSA2MAogICAgaWYgWyAkbWludXRlIC1nZSA2MCBdOyB0aGVuCiAgICAgIG1pbnV0ZT0wCiAgICAgIGhldXJlPSQoKGhldXJlICsgMSkpCiAgICBmaQoKICAgICMgUsOpaW5pdGlhbGlzYXRpb24gZGUgbGEgdmFyaWFibGUgaGV1cmUgc2kgZWxsZSBhdHRlaW50IG91IGTDqXBhc3NlIDI0CiAgICBpZiBbICRoZXVyZSAtZ2UgMjQgXTsgdGhlbgogICAgICBoZXVyZT0wCiAgICBmaQoKICAgIGNhdCA8PEVPRiB8IGt1YmVjdGwgLW4gJHt2ZWxlcm9OYW1lU3BhY2V9IGFwcGx5IC1mIC0KYXBpVmVyc2lvbjogdmVsZXJvLmlvL3YxCmtpbmQ6IFNjaGVkdWxlCm1ldGFkYXRhOgogIG5hbWU6ICR7c2NoZWR1bGVOYW1lfQogIG5hbWVzcGFjZTogJHt2ZWxlcm9OYW1lU3BhY2V9CnNwZWM6CiAgc2NoZWR1bGU6ICcke21pbnV0ZX0gJHtoZXVyZX0gKiAqIConCiAgdGVtcGxhdGU6CiAgICBzdG9yYWdlTG9jYXRpb246ICR7c3RvcmFnZUxvY2F0aW9ufQogICAgdHRsOiAyNDBoMG0wcwogICAgZGVmYXVsdFZvbHVtZXNUb1Jlc3RpYzogdHJ1ZQogICAgaW5jbHVkZWROYW1lc3BhY2VzOgogICAgICAtICR7bmFtZVNwYWNlfQpFT0YKICBmaQpkb25lCg==' | base64 -d | bash"]
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
          activeDeadlineSeconds: 600
          dnsPolicy: "ClusterFirst"
          serviceAccount: "projects-backup"
          serviceAccountName: projects-backup
