---
apiVersion: v1
kind: Secret
metadata:
  name: cloud-credentials
  namespace: {{ include "velero.namespace" . }}
type: Opaque
stringData:
  cloud: |
    [default]
    aws_access_key_id = {{ .Values.s3.accessKeyId }}
    aws_secret_access_key = {{ .Values.s3.secretAccessKey }}
