apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: oadp-operator
  namespace: "{{ .Values.namespace_adp }}"
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  installPlanApproval: Automatic
  name: oadp-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
