apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: oadp-operator-group
  namespace: "{{ .Values.namespace_adp }}"
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  targetNamespaces:
  - "{{ .Values.namespace_adp }}"
