apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: oadp-operator-group
  namespace: {{ include "operators.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  targetNamespaces:
  - {{ include "operators.namespace" . }}
