apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: oadp-operator-subscription
  namespace: "{{ .Values.namespace_adp }}"
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  channel: stable
  name: oadp-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
