kind: Secret
apiVersion: v1
metadata:
  name: {{ include "cpnConsole.fullname" . }}-server
  labels: {{- include "cpnConsole.server.labels" . | nindent 4 }}
data: 
  SESSION_SECRET: {{ .Values.global.keycloak.sessionSecret | b64enc }}
  KEYCLOAK_CLIENT_SECRET: {{ .Values.global.keycloak.clientSecrets.backend | b64enc }}
  DB_URL: {{ .Values.global.postgresql.dbUrl | default (printf "postgresql://%s:%s@%s-hl:%s/%s?schema=public" .Values.postgresql.global.postgresql.auth.username .Values.postgresql.global.postgresql.auth.password .Values.postgresql.fullnameOverride (.Values.postgresql.primary.service.ports.postgresql | toString) .Values.postgresql.global.postgresql.auth.database) | b64enc }}
  {{- if .Values.global.secrets -}}
  {{- include "cpnConsole.secret" .Values.global | indent 2 }}
  {{- end -}}
  {{- if .Values.server.secrets -}}
  {{- include "cpnConsole.secret" .Values.server | indent 2 }}
  {{- end -}}
