apiVersion: v1
kind: Service
metadata:
  name: {{ include "cpnConsole.fullname" . }}-server
  labels:
    {{- include "cpnConsole.server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.container.port }}
      protocol: TCP
  selector:
    {{- include "cpnConsole.server.selectorLabels" . | nindent 4 }}
