---
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: {{ .Values.IngressController.namespace }}
spec:
  clientTLS:
    clientCA:
      name: ""
    clientCertificatePolicy: ""
  httpCompression: {}
  httpEmptyRequestsPolicy: Respond
  httpErrorCodePages:
    name: ""
  namespaceSelector:
    {{- with .Values.IngressController.namespaceSelector.matchExpressions }}
    matchExpressions:
    {{- toYaml . | nindent 4 }}
    {{- end }}
  nodePlacement:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/infra: ""
  replicas: 2
  tuningOptions:
    reloadInterval: 0s
  unsupportedConfigOverrides: null