apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    ipfailover: {{ .Values.rie.name }}
  name: ipfailover-keepalived-rie
  namespace: {{ include "ingress-keepalived.namespace" . }}
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      ipfailover: {{ .Values.rie.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        ipfailover: {{ .Values.rie.name }}
    spec:
      containers:
      - env:
        - name: OPENSHIFT_HA_CONFIG_NAME
          value: {{ .Values.rie.name }}
        - name: OPENSHIFT_HA_NETWORK_INTERFACE
          value: br-ex
        - name: OPENSHIFT_HA_VIRTUAL_IPS
          value: {{ .Values.vip.rie }}
        - name: OPENSHIFT_HA_MONITOR_PORT
          value: "0"
        - name: OPENSHIFT_HA_REPLICA_COUNT
          value: "2"
        - name: OPENSHIFT_HA_VRRP_ID_OFFSET
          value: "{{ .Values.id_vrrp.rie }}"
        - name: OPENSHIFT_HA_USE_UNICAST
          value: "false"
        - name: OPENSHIFT_HA_IPTABLES_CHAIN
          value: INPUT
        - name: OPENSHIFT_HA_CHECK_SCRIPT
          value: /etc/keepalive/check-script.sh
        - name: OPENSHIFT_HA_PREEMPTION
          value: preempt_delay 300
        - name: OPENSHIFT_HA_CHECK_INTERVAL
          value: "2"
        image: quay.io/openshift/origin-keepalived-ipfailover
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - pgrep
            - keepalived
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: openshift-ipfailover
        ports:
        - containerPort: 30060
          hostPort: 30060
          protocol: TCP
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /lib/modules
          name: lib-modules
          readOnly: true
        - mountPath: /host
          mountPropagation: HostToContainer
          name: host-slash
          readOnly: true
        - mountPath: /etc/sysconfig
          name: etc-sysconfig
          readOnly: true
        - mountPath: /etc/keepalive
          name: config-volume
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: {{ .Values.serviceaccount.name }}
      serviceAccountName: {{ .Values.serviceaccount.name }}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /lib/modules
          type: ""
        name: lib-modules
      - hostPath:
          path: /
          type: ""
        name: host-slash
      - hostPath:
          path: /etc/sysconfig
          type: ""
        name: etc-sysconfig
      - configMap:
          defaultMode: 493
          name: check
        name: config-volume