{{- if .Values.client.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "cpnConsole.fullname" . }}-client
  labels:
    {{- include "cpnConsole.client.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "cpnConsole.fullname" . }}-client
  minReplicas: {{ .Values.client.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.client.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.client.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.client.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.client.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.client.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
