{{- if or .Values.global.secrets .Values.client.secrets }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "cpnConsole.fullname" . }}-client
  labels: {{- include "cpnConsole.client.labels" . | nindent 4 }}
data: 
  {{- if .Values.global.secrets -}}
  {{- include "cpnConsole.secret" .Values.global | indent 2 }}
  {{- end -}}
  {{- if .Values.client.secrets -}}
  {{- include "cpnConsole.secret" .Values.client | indent 2 }}
  {{- end -}}
{{- end -}}
