{{- if .Values.ovh }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.rook_ceph_operator.name }}
  namespace: {{ .Values.rook_ceph_operator.namespace }}
data:
  CSI_PLUGIN_TOLERATIONS: |
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
      operator: Exists
{{- end }}
