---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: etcd-backup-sa-privileged
  namespace: "{{ .Values.etcd_backup_ns }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: use-privileged-scc
subjects:
  - kind: ServiceAccount
    name: etcd-backup