---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: use-privileged-scc
  namespace: {{ include "etcd-backup.namespace" . }}
  {{- with .Values.rules }}
  rules:
  {{- toYaml . | nindent 4 }}
   {{- end }}
