---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: use-privileged-scc
  namespace: {{ include "etcd-backup.namespace" . }}
rules:
  {{- with .Values.rules }}
  {{- toYaml . | nindent 2 }}
  {{- end }}