---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cnpg-operator-sa-anyuid
    {{- include "cnpg-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: anyuid
subjects:
  - kind: ServiceAccount
    name: {{ include "cnpg-operator.serviceAccountName" . }}